// SERVER-ONLY skill playbooks — the full craft texts behind each skill.
// Loaded mid-run via the load_skill tool (and re-injected on approval
// continuations). Do NOT import from client components: the client-safe
// registry is lib/chat-hub-skills.ts, which only carries token counts.
// This module must not import lib/chat-hub-agent (import cycle).

import { usableCreateModels } from '@/lib/chat-hub-models'
import { skillOn, type SkillSet } from '@/lib/chat-hub-skills'

export type PlaybookCtx = { skills: SkillSet }

const GD = [
  'MEDIA CRAFT FUNDAMENTALS — use this vocabulary in every prompt, whatever the model: shot types (extreme close-up, close-up, medium, wide, establishing, aerial); lens language (35mm documentary feel, 50mm natural, 85mm portrait compression, macro); lighting setups (golden hour, overcast soft light, Rembrandt, rim light, neon practicals, high-key, low-key); composition (rule of thirds, leading lines, negative space, foreground depth, symmetry); color grading (teal-and-orange, desaturated pastel, high-contrast noir, warm film stock). For multi-asset campaigns: pick ONE coherent aesthetic and repeat its exact descriptors verbatim across every asset — consistency comes from repeated wording, not vibes.',
  'GRAPHIC DESIGN RULES — you are also the art director; apply these to EVERY layout decision, especially text placement with edit_image:',
  '1. LOOK FIRST: before placing anything, study the image — identify the focal point (face, product) and the largest area of clean negative space. Text goes IN the negative space; it never covers the subject or sits on busy texture.',
  '2. EYE PATH: viewers scan posters in a Z-pattern (top-left → top-right → diagonal → bottom). Put the headline on the first stroke of that path — upper third or lower third, anchored to a rule-of-thirds line (x at ~33% or ~66% of width). Dead-center only when the composition itself is symmetric.',
  '3. NUMBERS, not vibes: safe margins ≥5% of each dimension from every edge (a 2000px-wide image → nothing closer than 100px to an edge). Poster headline size ≈ imageHeight/10 to /14; subline 45-60% of headline size; max TWO text sizes per layout. One alignment axis for all text blocks (all left-aligned to the same x, or all centered) — mixed alignment reads amateur.',
  '4. CONTRAST = LEGIBILITY: light text needs a genuinely dark region behind it (and vice versa). If the only good spot is busy, prepare it first — draw a translucent dark rect scrim ({op:"shape",shape:"rect",fill:"#000000",opacity:0.45}, the classic poster move), region_blur the rect lightly, or add a stroke outline to the text — THEN place the text. Never drop white text on a mid-tone area and hope.',
  '5. BALANCE: a text block has visual weight. Offset it against the subject (subject on the left → text block on the right). When a layout feels wrong: more negative space, fewer elements, bigger size contrast.',
  '6. VERIFY LIKE AN ART DIRECTOR: after every text/layout edit, record_evaluation must judge: is the focal point intact? does the eye travel headline → subject → detail? margins and alignment consistent? contrast sufficient at a glance from 2 meters? If any answer is no, verdict=revise with the exact fix (new x/y/size).',
  'GESTALT PRINCIPLES — the viewer\'s brain groups before it reads; design WITH it: PROXIMITY (things close together read as one unit — caption hugs its image, unrelated blocks get double spacing), SIMILARITY (same color/size/shape = same family — style every price tag identically), CLOSURE (suggested shapes intrigue — a logo cropped by the frame edge feels bigger than one floating), FIGURE-GROUND (strong silhouettes flip backgrounds into shapes — check what the negative space accidentally draws), CONTINUATION (eyes follow lines and edges past their end — aim every strong line at something that deserves attention, never off-canvas).',
  'HIERARCHY LEVELS — exactly THREE reads, every element assigned to one: LEVEL 1 the 3-second billboard read (headline + hero image + brand — what a driver catches), LEVEL 2 the 30-second engaged read (subline, key benefit, CTA), LEVEL 3 the detail read (specs, legal, credits). If two elements compete at Level 1, DEMOTE one — co-champions mean no champion. Size, weight, contrast and position are the demotion tools; a layout with five "important" things has zero.',
].join('\n')

const COLOR_THEORY = [
  'COLOR THEORY — think like a colorist BEFORE generating or editing:',
  '- VALUE FIRST: composition reads in VALUE (light/dark) before hue. Plan 3 values — dominant field, secondary, focal accent — and check them with a mental squint test: if the focal point does not pop in grayscale, no hue choice will save it. Prompt values explicitly ("dark moody background, brightly lit subject").',
  '- HARMONIES and when to use them: complementary (max energy, ads/sports — let ONE side dominate ~80/20), split-complementary (energy with less tension — the safe bold choice), analogous (calm, cohesive, editorial — add one value jump so it does not flatline), triadic (playful, toys/kids — mute two, saturate one), monochromatic (elegant, moody — vary value and saturation hard). Name the harmony in the prompt: "analogous blue-teal palette with a single warm amber accent".',
  '- SATURATION DISCIPLINE: full saturation is a spotlight — spend it ONLY at the focal point. Equal saturation everywhere = visual noise; equal MUTED saturation = mud. Desaturate backgrounds 30-50% relative to the subject. The most common amateur tell is everything at 100% chroma.',
  '- TEMPERATURE = DEPTH and light logic: warm advances, cool recedes — warm subject on cool field pops (teal-and-orange exists for a reason). Real light opposes: warm key light → cool shadows (and vice versa); prompt it ("golden key light, cool blue shadows") for instant dimensionality.',
  '- 60-30-10: dominant hue ~60%, secondary ~30%, accent ~10%. The accent belongs on the thing you want clicked/read — CTA, headline, product. One accent; a second accent halves the first\'s power.',
  '- MOOD PALETTES (usable hexes — adapt, don\'t copy blindly): luxury = near-black #0d0b0e + champagne gold #c9a96a + ivory; tech = deep navy #0a1628 + electric cyan #22d3ee + white; calm/wellness = sage #9caf88 + warm sand #e8dcc8 + off-white; energy/sport = black + acid #ccff00 or red-orange #ff4123; romance = blush #e8b4b8 + burgundy #6d1a36 + cream; horror/tension = desaturated everything + one blood accent.',
  '- GRADING VOCABULARY for prompts: teal-and-orange (blockbuster pop), bleach bypass (gritty, desaturated highlights), pastel wash (soft, dreamy, lifted blacks), high-contrast noir (crushed blacks, hard whites), warm film stock (golden, nostalgic), cross-process (shifted casts, editorial edge). Name ONE grade and repeat it verbatim across a set.',
  '- SKIN: keep skin hues inside the narrow orange-pink band and vary VALUE not hue; green/grey casts on skin read as sickly instantly. On stylized work, skin can shift — but shadows on skin should lean warm-red or cool-purple, never green.',
  '- LEGIBILITY & VIBRATION: text needs VALUE contrast with its ground, not just hue contrast — red on blue at equal value vibrates and is unreadable. Never place complementary hues of equal value against each other at an edge that matters.',
  '- STYLE-SPECIFIC SYSTEMS: anime/cel = saturated flats + desaturated painterly backgrounds; watercolor = low saturation, white-of-the-paper as lightest value; cyberpunk = magenta/cyan neons on near-black, nothing mid-value; vintage = no pure white or black — ivory #f3ecd9 and soft brown-black #2a211c, muted accents; corporate/clean = one brand hue + greys, saturation only in the accent.',
  '- IN EDITS: pull every color FROM the artwork (name the dominant hex + one existing accent hex by looking); scrims = the dominant hue darkened, not #000000 (except noir); text in the artwork\'s accent or a neutral; introducing a foreign hue is the fastest way to make an edit look pasted on.',
].join('\n')

const LIGHTING = [
  'LIGHTING MASTERY — light IS the image; decide the light before the subject:',
  '- QUALITY: hard light (small/distant source — sun, bare bulb) = drama, texture, crisp shadows; soft light (big/close source — softbox, overcast, window) = beauty, calm, forgiving skin. Source size relative to subject controls softness — prompt it: "lit by a large window camera-left" vs "single bare bulb overhead".',
  '- DIRECTION: front light flattens (mugshot); side light reveals texture and form (the artist\'s default); back light silhouettes and rims (separation, mystery); top light dignifies (museum); under-light unsettles (horror). Name direction + height in every serious prompt.',
  '- NAMED PORTRAIT SETUPS (use the names — models know them): Rembrandt (45° side-high key, triangle of light on the far cheek — painterly gravitas), butterfly (frontal-high, shadow under the nose — glamour), split (pure side, half-face dark — duality/tension), loop (soft everyday portrait default), rim/kicker (edge light from behind — separation on dark sets), clamshell (soft above + fill below — beauty ads).',
  '- RATIOS: key:fill contrast sets the mood — 2:1 gentle commercial, 4:1 dimensional editorial, 8:1+ noir/dramatic. Prompt as "soft fill" vs "deep unfilled shadows".',
  '- MOTIVATED LIGHT: every light needs a believable source in-world (window, lamp, neon sign, fire, screen glow). Unmotivated studio light in a narrative scene reads fake. Practicals IN frame (a lamp, candle, sign) add depth and justify the look.',
  '- TIME-OF-DAY SYSTEM: golden hour (warm, long soft shadows — romance/nostalgia), blue hour (cool ambient + warm practicals — cinematic melancholy), overcast (giant softbox — even, honest), harsh noon (unflattering unless brutalist/desert drama), night sodium/neon (color-cast storytelling).',
  '- CHIAROSCURO & VOLUMETRICS: pools of light in darkness for old-master drama; god rays / hazy shafts for atmosphere — powerful but one per image, and only where air would carry haze (dust, mist, smoke).',
  '- LIGHT AS COMPOSITION: the brightest area is the FIRST read — put it on the subject or the eye goes wrong; use light paths (windows, streaks, falloff gradients) to steer the eye toward the focal point; darkness is negative space.',
  '- MOOD MAP: romance = warm, soft, backlit glow; tension = hard single-source side light, deep ratios; luxury = controlled specular gradients on dark sets, no flat fill; innocence/health = bright high-key, minimal shadow; grief = cool overcast flatness.',
  '- LIGHT EVALUATION HOOKS: ONE light story per image — do all shadows agree on direction and hardness? Do refs and composited elements share the scene\'s light? Is the brightest point where the eye SHOULD land? Inconsistent light = verdict revise.',
].join('\n')

const STYLE_LEXICON = [
  'STYLE LEXICON — art movements and design eras as deployable prompt language. Deploy an era by NAME plus 3-4 of its descriptors, and repeat the exact wording across a set:',
  '- BAUHAUS: geometric primitives, primary colors + black, functional asymmetry, "form follows function" poster look. For: bold modernist posters, education/culture branding.',
  '- SWISS/INTERNATIONAL: strict grid, huge grotesque sans type (Helvetica-class), red-black-white, asymmetric layouts, objective photography. For: editorial, corporate authority, timeless poster work.',
  '- ART DECO: gold geometry, stepped forms, sunburst fans, symmetric luxury, 1920s glamour. For: premium spirits, hotels, gala/event posters.',
  '- ART NOUVEAU: organic whiplash curves, botanical frames, muted naturals + gold, Mucha-style figure vignettes. For: cosmetics, tea/botanicals, romantic illustration.',
  '- BRUTALISM: raw concrete texture, oversized mono/system type, harsh contrast, deliberate anti-polish, exposed structure. For: streetwear, music, edgy web/poster looks.',
  '- MEMPHIS: squiggles and confetti geometry, clashing pastels + primaries, playful chaos, 1980s Milan. For: youth brands, playful campaigns.',
  '- Y2K: liquid chrome, lens flares, translucent plastic, bubble type, silver-blue optimism, early-3D gradients. For: nostalgia-tech, music, fashion capsules.',
  '- VAPORWAVE: magenta-cyan gradients, classical statues, wireframe grids, sunset stripes, ironic nostalgia. For: internet-culture visuals, album art.',
  '- MID-CENTURY MODERN: flat textured illustration, mustard/teal/burnt-orange, atomic shapes, friendly geometry. For: approachable brand illustration, posters.',
  '- BAROQUE: dramatic diagonals, deep chiaroscuro, rich fabrics, opulent excess, Caravaggio light. For: prestige drama, perfume, fine dining.',
  '- IMPRESSIONISM: broken color dabs, light over line, outdoor luminosity, soft edges everywhere. For: dreamy lifestyle, romantic scenes.',
  '- UKIYO-E: flat stacked perspective, bold keyline outlines, woodblock texture, wave/wind motion patterns, limited ink palette. For: striking posters, japonisme briefs.',
  '- MINIMALISM vs MAXIMALISM: minimal = one subject, vast negative space, ≤2 colors, whisper type (luxury, tech); maximal = dense pattern-on-pattern, saturated everything (fashion editorial, festivals). Commit fully — the middle reads indecisive.',
  '- MIXING RULE: ONE dominant movement + at most ONE accent influence, both named explicitly ("Swiss grid layout with Y2K chrome accents"). Blending three eras produces mush. Keep the era wording verbatim across every asset of a set.',
  '- ERA EVALUATION HOOK: anachronism check — a Deco poster with a geometric-sans-only lockup, or Baroque light in a Memphis layout, is a style violation = revise naming the intruding element.',
].join('\n')

const PHOTOGRAPHY = [
  'PHOTOGRAPHY CRAFT — prompt like the photographer who shot it:',
  '- FOCAL LENGTH PSYCHOLOGY: 16-24mm = environmental drama, exaggerated foregrounds, architecture (distorts faces up close); 35mm = documentary honesty, subject-in-context; 50mm = human-eye neutrality; 85mm = the portrait classic (flattering compression, melty bokeh); 135mm+ = paparazzi/voyeur compression, stacked backgrounds; macro = obsessive detail worlds. NAME the lens feel in photoreal prompts.',
  '- APERTURE/DOF: "shot at f/1.4" = razor focus plane, dreamy isolation, glowing bokeh; f/2.8-4 = subject sharp, background readable; f/8-11 = product/landscape everything-sharp. Match DOF to intent: isolation flatters, deep focus informs.',
  '- SHUTTER LANGUAGE: frozen action ("1/1000s, crisp droplets suspended"), motion blur for energy ("slow shutter, streaking crowd"), long exposure ("light trails, silky water"), panning ("sharp subject, streaked background").',
  '- FILM STOCKS AS GRADE SHORTHAND: Portra 400 (warm gentle skin, wedding/editorial gold standard), Ektachrome (cool clean editorial), Kodak Gold (sunny nostalgia), Tri-X 400 (gritty black-and-white photojournalism), Cinestill 800T (tungsten nights, red halation on lights), Fuji Velvia (punchy landscape saturation). "Shot on X" is the fastest way to a coherent grade.',
  '- FORMATS: 35mm (honest grain, reportage), medium format (creamy tonality, fashion/luxury stillness), large format (surgical stillness, product/architecture), Polaroid/instant (borders, lifted blacks, intimacy), phone camera (see UGC skill).',
  '- FRAMING CONVENTIONS: headroom (a little, not a lot), lead room in the gaze/motion direction, eye-level = equality, low angle = power/monumentality, high angle = vulnerability/overview, Dutch tilt = unease (use rarely and on purpose).',
  '- LENS ARTIFACTS — invoke or ban deliberately: flare (cinematic warmth or ban with "no lens flare"), vignette (subtle focus aid), chromatic aberration/halation (lo-fi character). Silence = model sprinkles them randomly.',
  '- PHOTO EVALUATION HOOKS: does DOF match the claimed aperture (f/1.4 with everything sharp = fake)? Does perspective match the focal length (85mm portrait with wide-angle nose distortion = revise)? Does grain/halation match the claimed stock/format? A "photo" with rendering-engine gloss = revise.',
].join('\n')

const MATERIALS = [
  'MATERIALS & SURFACES — surfaces read as real only when their light behavior is named:',
  '- METALS: brushed ("anisotropic streaked highlights, soft satin sheen") vs polished ("mirror speculars, crisp environment reflections") vs anodized/matte ("even color, tight soft highlight"). Always give metal a reflection subject: "reflecting the softbox as a long gradient" — metal with nothing to reflect looks like plastic.',
  '- GLASS & TRANSPARENTS: refraction bending what\'s behind, bright edge highlights, caustic light patterns on the surface below; "clean specular highlights, no blown-out hotspots". Colored liquid in glass doubles the difficulty — name both the glass edge light and the liquid\'s translucency.',
  '- FABRICS BY WEAVE: silk/satin (directional sheen, liquid folds), wool/knit (matte depth, visible fiber, chunky shadow in the knit), denim (twill diagonal, worn high-points), velvet (light-trapping pile — deep rich shadow core, edge glow), linen (dry crease texture), leather (grain + subtle cream speculars, wear at flex points).',
  '- SKIN: subsurface scattering — light glows THROUGH at ears, fingers, nostril edges ("warm subsurface glow at the ears"); natural oil zones (T-zone speculars) vs matte cheeks; visible pores at close range. The wax-figure tell = no SSS + uniform speculars = revise.',
  '- LIQUIDS: name viscosity (water splashes thin and chaotic, honey ropes and folds, cream sheets); condensation droplets for cold ("beaded condensation, one running drip"), meniscus where liquid meets glass, frozen splash crowns for action shots.',
  '- WOOD & STONE: wood grain has DIRECTION — name it relative to the cut ("long grain along the tabletop, end-grain at the edge"); stone: honed (soft matte) vs polished (deep reflective) vs rough-hewn (shadowed tooth). Repetitive tiling texture = CG tell = revise.',
  '- WEAR TELLS THE STORY: showroom-new (flawless, full speculars) vs lived-in (edge wear on corners, fingerprints near handles, patina in recesses, dust in crevices). Choose one and prompt it — half-worn objects read as rendering errors.',
  '- MATERIALS NEED THE RIGHT LIGHT: speculars need gradient light sources to shine (big softbox = luxury metal look), SSS needs back/rim light to glow, fabric weave needs raking side light, transparents need something bright behind them. Pair this skill with the lighting playbook on product heroes.',
  '- MATERIAL EVALUATION HOOK: would a product photographer believe this surface? Plastic-looking metal, wax skin, weightless fabric, or reflection-free glass = verdict revise naming the material that failed.',
].join('\n')

const ANATOMY = [
  'ANATOMY & FIGURE — classical training for generating, sketching and JUDGING bodies:',
  '- PROPORTION CANON (adult ≈ 7.5-8 heads tall; use head-height as the ruler): chin→nipple line = 1 head; navel/elbows ≈ 3 heads down; crotch = the body\'s MIDPOINT (4 heads); fingertips reach mid-thigh; knees ≈ 5.5-6; shoulder width ≈ 2-3 heads (broader masculine, narrower feminine); hand height ≈ face height (chin to hairline); foot length ≈ forearm. The commonest AI errors: legs too short (crotch below midpoint), hands too small, arms ending high.',
  '- AGE SCALES: toddler ≈ 4 heads (huge cranium, short limbs), child ≈ 5-6, teen ≈ 6.5-7, adult 7.5-8, heroic/fashion 8.5-9 (stylization, not realism). Elderly: slight height loss, forward head carriage, narrower shoulders. A child drawn at adult proportions with a small body reads as a creepy miniature adult = revise.',
  '- GESTURE & LINE OF ACTION: every pose hangs on ONE sweeping line from head through spine to weight-bearing foot — S-curves live, straight lines are stiff. Prompt the gesture, not the parts: "weight sunk into the back hip, spine curving away from the raised arm".',
  '- CONTRAPPOSTO & BALANCE: weight on one leg → that hip rides HIGH, shoulders counter-tilt the OPPOSITE way, spine takes an S. Center of gravity (pit of neck) must stack over the supporting foot — a lean requires a counterweight (arm, bag, other leg) or the figure reads as falling. Check every standing figure for hip-shoulder counter-tilt; matched tilts = mannequin stiffness.',
  '- SKELETAL LANDMARKS that show through skin (name them for realism): clavicle ridge, pit of neck, acromion (shoulder corner), elbow point, wrist knobs, ASIS hip points, patella, ankle bones (inner higher than outer), shoulder blades, C7 bump at neck base.',
  '- MUSCLE MASSES simplified (drawing-level, not medical): deltoid teardrop caps the shoulder; biceps/triceps oppose; forearm = two twisting masses (widest near elbow); pecs fan INTO the deltoid; lats make the back\'s V; abs = rows ending at navel by the 3rd; glutes are high and round, not low; quads = teardrop bulging inward above the knee; calf heads asymmetric (inner sits LOWER). Muscles interlock at angles — sausage-limb smoothness is a failure tell.',
  '- THE HAND SYSTEM (the #1 AI failure zone): FIVE fingers — count them EVERY time, on EVERY visible hand, before anything else. Structure: palm ≈ finger length; knuckles form an ARC not a line; middle finger longest; thumb opposes from the SIDE with 2 visible segments and its own palm mass; fingers curl toward the wrist\'s pinky side; nails only visible from the back. Fingers bend at 3 joints in ONE direction. When hands keep failing: re-prompt with an explicit hand pose ("hands relaxed at sides", "holding the cup with four fingers visible, thumb in front") or choose a pose that naturally hides them (pockets, crossed arms, behind back).',
  '- HEAD CONSTRUCTION: eyes sit at the VERTICAL MIDPOINT of the skull (beginners place them too high); face is five eye-widths across with one eye-width between the eyes; ears span brow-line to nose-base (in profile, behind the jaw\'s midpoint); nose-base→chin splits in half at the lower lip. Three-quarter view: the far eye foreshortens, the nose overlaps the far cheek. Both eyes on the SAME level line in a frontal face — mismatched eye lines are a top artifact.',
  '- FORESHORTENING: sell depth with OVERLAP + width change, not length ("the forearm overlaps the upper arm, fist large toward camera") — limbs are cylinders in perspective; a limb pointed at camera nearly vanishes in length but GROWS in width. No overlap cue = broken-looking limb.',
  '- JOINT LIMITS (violations = instant revise): elbows and knees are HINGES — one direction only, never hyperextended backward; forearms rotate, upper arms don\'t twist past ~90°; fingers can\'t bend backward; necks turn ~80° max — a head at 120° to the shoulders is broken. Count limbs and joints per figure in multi-figure scenes; extra/merged limbs hide where figures overlap.',
  '- FABRIC OVER ANATOMY: cloth reveals the body at CONTACT points (shoulders, chest, hips, knees) and hangs free between them; tension folds radiate FROM joints toward the action; the body must read THROUGH the clothes — floating fabric with no landmarks beneath = revise.',
  '- MOTION POSES: walking/running = opposite arm and leg forward, spine rotated; a jump needs anticipation or follow-through (never frozen mid-pose with relaxed limbs); action shots want the line of action exaggerated ~20% beyond natural.',
  '- PROMPTING APPLICATION: specify pose anatomically ("contrapposto, weight on the right leg, left hip dropped, chin turned three-quarter"), state camera height against the figure (hip-height heroic, eye-level honest), and for stylized work SCALE the canon knowingly (chibi 2-3 heads, anime 6.5-7.5, heroic 8.5) — stylization changes the ratios, never the joint rules.',
  '- FIGURE EVALUATION DRILL (runs with the artifact checklist on EVERY figure): finger count per visible hand → joint bend directions → head:body ratio vs the intended canon → eye line level → hand size vs face → crotch at midpoint → hip/shoulder counter-tilt on standing figures → limb count where figures overlap → does the body read through the clothes? ANY failure = verdict revise naming the exact body part and the fix.',
].join('\n')

const PHOTOSHOP = [
  'DESIGN EXECUTION PLAYBOOK — build edits in LAYERS, bottom to top (prep → scrim → text → accents), all in ONE chained edit_image call:',
  '- Lower-third hero (the default poster treatment): gradient scrim rect over the bottom ~35% ({op:"shape",shape:"rect",gradient:{from:"#000000",from_opacity:0,to:"#000000",to_opacity:0.75,direction:"down"}}), headline in impact/condensed at height/12 with align:"center" (x = canvas midpoint) or left-aligned on the 33% line, subline in sans at 50% of headline size one spacing-unit below, and a thin accent rule (rect, 3-5px tall, accent color) between them.',
  '- Badge: circle in an accent color + short centered text over it; place in the corner OPPOSITE the focal point, radius ≈ height/10.',
  '- Caption bar: pad the bottom by ~12% in a near-black or image-sampled color, then place text inside the new bar — zero overlap with the artwork.',
  '- PALETTE DISCIPLINE: sample colors FROM the image — look at it, name the dominant hue and one high-contrast accent that already exists in the artwork, and use those exact hexes for scrims/rules/badges. Never introduce foreign colors unless the user gave brand colors.',
  '- TYPE PAIRING: impact or condensed for headlines, sans for sublines/body; script only as a single accent word; never more than 2 families per design.',
  '- SPACING SYSTEM: pick one unit ≈2% of image height; every gap and margin is a multiple of it. Every element must share an edge or centerline with another element — nothing floats arbitrarily.',
  '- EXACT DIMENSIONS: edit_image results state the precise pixel size (e.g. "result is 2048x1152px") — compute coordinates from those numbers, never estimate off the preview, and recompute after crop/pad changes the canvas.',
  '- REMOVING UNWANTED TEXT/OBJECTS: ONE edit_image call on the original using {op:"patch"} — copy a clean area of the same background over the offending rect, then optionally region_blur the seam. NEVER build multi-call crop→stretch→overlay chains: the intermediate crops become useless strips in the feed and you lose track. If patch still looks wrong after 2 attempts, STOP and switch to a generative edit (create_media with the image as reference: "remove the text, keep everything else pixel-identical").',
  'STYLE-MATCHED EDITING — an edit must look like it was part of the original render. BEFORE editing, NAME the content\'s style (photoreal / cel-anime / painterly / flat graphic / vintage photo) and match every added element to it:',
  '- Photoreal: soft-edged scrims at ≤0.5 opacity in the image\'s own darkened dominant hue; never pure #000000/#ffffff (sample near-black/near-white from the image); subtle text strokes; a hint of region_blur under overlays to sit them into the grain.',
  '- Cel/anime & flat graphic: hard-edged flat shapes in the artwork\'s EXACT palette hexes, full opacity, no gradients unless the art already uses them; condensed/impact type suits cel, geometric sans suits flat design.',
  '- Painterly: avoid crisp vector shapes over brushwork — prefer text with a soft wide stroke, or place type in genuinely quiet areas; scrims read as fog, keep them very low opacity.',
  '- Vintage: ivory (#f3ecd9-range) instead of white, brown-black instead of black, muted accent colors; serif or period-appropriate type; slight opacity (0.9) on text helps it sit into aged paper/print.',
  '- THE NATIVE TEST in every layout evaluation: could a viewer believe the text/shapes were rendered WITH the image? If any element floats on top stylistically (wrong palette, wrong edge quality, wrong era), verdict=revise naming the mismatched element.',
  'SUBJECT MASKING — remove_background and silhouette give PIXEL-PERFECT AI auto-masks of the dominant subject (people, products). Never fake a silhouette with polygons, and never claim precise masking is impossible:',
  '- White/color silhouette over the original (the classic poster move): ONE op — {op:"silhouette",color:"#ffffff"} (default composites over the image). Silhouette alone for logos/posters/stencils: on_original:false → solid shape on transparency.',
  '- Background removal: {op:"remove_background"} → subject on transparency; chain pad (solid color field) or use the result URL with overlay in a later call to put the subject on any new background.',
  '- Color-pop (color subject on mono background): call 1 on the original: remove_background → note the result URL; call 2 on the original: grayscale, then {op:"overlay",image_url:<cutout URL>,x:0,y:0} — dimensions match 1:1.',
  '- Sticker/outline feel: silhouette on_original:false in an accent color, overlaid at a small offset BEHIND the cutout (drop-shadow recipe) = outlined die-cut look.',
  '- Echo/shadow-double poster: a brand-color silhouette composited slightly offset behind the subject in the original.',
  '- LIMITS: the mask targets the DOMINANT subject — it cannot pick one person out of a crowd or mask a single body part. For partial/selective masks, use a generative edit instead and say so.',
  '- MASK QC — every cutout comes back attached: INSPECT it (record_evaluation) BEFORE compositing. Floating junk blobs are removed automatically, but background patches ATTACHED to the subject (a piece of wall between arm and body, background hugging the outline) survive — re-run with trim_regions:[{x,y,width,height}] rectangles (source-image pixels) to zero them out, or use overlay crop to keep only the clean part. Compositing a contaminated cutout is an automatic evaluation fail.',
  'CUTOUT FLAT-SIDE DOCTRINE — non-negotiable. A cutout inherits a dead-straight edge wherever the body ran out of the source frame (cropped arms, torso cut at the waist, hair sliced at the top). A floating flat edge in open space is the #1 amateur tell in composite work. BEFORE placing any cutout, name its flat sides (which of the 4 source edges the subject touches), then make EVERY flat side disappear using one of these, in preference order:',
  '- 1. BLEED: place + scale the cutout so each flat side runs OFF the canvas edge (or overshoots it). A figure cut at the waist sits at the bottom edge, never floating mid-air. This is the standard pro move — crop lines live at the frame, not inside it.',
  '- 2. TUCK: hide the flat edge BEHIND another element — a panel, color bar, badge, title block, or another figure. Layer order is paint order: draw the covering element AFTER the cutout.',
  '- 3. TRIM: overlay crop:{x,y,width,height} (source-image pixels) cuts the cutout down to its clean region — drop a truncated forearm or half-cropped shoulder entirely and use only the intact head/torso. Better to show less of a person cleanly than more of them with sliced limbs.',
  '- 4. FRAME IT: put the cutout inside a deliberate device — circle badge, sticker with border, panel window — so the cut edge reads as designed cropping, not an accident.',
  '- NEVER: a flat cut edge floating against open background, a sliced limb mid-canvas, or a figure whose straight bottom edge hovers above other art. If none of the four strategies fits, say so and choose a different composition.',
  '- NEVER paste a raw rectangular region of a source photo as a "subject" — a box of leftover background around a head is an instant fail. Subjects enter a composite ONLY as remove_background cutouts (or deliberately framed panels with visible intentional borders).',
  '- Self-check before finishing ANY composite with cutouts: trace each cutout\'s outline — does any straight source-frame edge show against open space? If yes, fix it before presenting.',
  'TEXT OCCUPANCY MAP — text may NEVER sit on text. Before placing ANY text, logo block or big shape, list what already occupies that region of the canvas (subjects, earlier text ops, badges). If the region is taken: relocate, shrink, or put a scrim between. Display type gets its own reserved clear band — plan the bands FIRST (title band, subline band, credits band) and place everything else around them. After the last op, walk every text string and confirm it is fully visible and legible; one covered word = the edit failed.',
  'WHITE SPACE MASTERY — empty area is a MATERIAL, not an absence; the difference between negative space and leftover space is a JOB. Negative space earns its place by doing one of: FRAMING (it shapes and isolates a subject or type block, giving it power), BREATHING (type and subjects get proportional clear zones — cramped kills luxury), DIRECTING (the eye path crosses it on the way between anchors), or BALANCING (a deliberate asymmetric mass offsetting a heavy element). Leftover space does none of these — it is simply where nothing happened (a bare top-left quadrant of stars nobody routed the eye through). THE QUADRANT AUDIT: before finishing, check all four quadrants and name each one\'s job; a quadrant with no job gets one — extend/rescale a subject into it, anchor it with type/badge/credits, vary its texture toward a focal glow, or REBALANCE the layout so the space becomes a deliberate frame. RATIO SENSE: minimal/luxury pieces run 50-70% negative space ON PURPOSE (one strong anchor, generous type margins); dense posters run 20-40%; either works — drifting between them by accident does not. Sketch the full-canvas layout (bands + subject zones + the job of every empty region) BEFORE the first op.',
  'FILTER GRADES — {op:"filter",name,strength?} is the one-op finishing grade: noir (b/w + contrast + vignette), bw (clean high-contrast mono), vivid (punchy saturation), matte (lifted blacks, soft), warm / cool (temperature push), vintage (faded warm film), golden (golden-hour glow), dreamy (soft bloom), cinematic (teal-orange + vignette). Order matters: a filter grades EVERYTHING painted so far — run it after compositing but BEFORE text ops when type must stay pure ink, or at the very end for a unified cast over everything. strength 0.3-0.6 is usually the pro dose; 1.0 is a statement. One grade per piece — stacking filters muddies.',
  'STARFIELD & NIGHT SKIES — {op:"starfield"} paints a realistic procedural star sky (halos + flares on hero stars, deterministic per seed). MOTIVATION GATE: starfield ONLY when the concept\'s world actually contains a night/space sky (sci-fi, cosmic, night scenes) — it is NOT default decoration, and reaching for it on every brief is spam. Other worlds pull their atmosphere from the ASSET LIBRARY instead (search_refs/dataset folders: smoke, fog, bokeh, paper/film textures, light leaks — overlay + screen/soft-light/multiply at low opacity); when no matching asset exists, a clean gradient or color field beats an off-concept effect every time. When a starfield IS motivated: background fields first → starfield → subjects/text on top; density 0.5 sparse - 2 dense; re-roll via seed; DEFAULT = the ENTIRE canvas (omit region unless a distinct floor/ground zone exists). Never fake stars with circle ops.',
  'MULTI-SUBJECT STAGING — when compositing 2+ cutouts, assign each subject its own zone BEFORE any op (opposite thirds; different scales for depth). Overlap is allowed ONLY as deliberate depth staging — one subject\'s face may NEVER be covered by another subject, text, or graphics. State each subject\'s zone and scale in your reply before compositing; if zones collide, shrink or re-anchor first. Title text goes in its reserved band, never across a face.',
  'CANVAS RESOLUTION — derive the canvas size from the SOURCES, not habit. Check every source\'s pixel dimensions first (edit results state theirs; dataset originals are full-res). Size the canvas so each cutout lands at or BELOW its native resolution — downscaling sources is fine, upscaling past ~1.1× smears the detail the source paid for. Posters built from 3000px+ sources deserve a 2400×3600-plus canvas; picking a small canvas throws away detail, picking one far beyond the sources forces upscaling. State the chosen canvas size and the largest source dimension that justified it in the plan.',
  'THE STACK PLAN — MANDATORY before ANY multi-cutout composite, printed in your reply as a short list, one line per cutout: "[name]: missing = right shoulder + below waist; strategy = tuck cut behind B / bleed bottom off-canvas; order = 1 (back)". Derive the order FROM the inventory: the MOST COMPLETE subject renders ON TOP (later op); every truncated edge tucks BEHIND an intact body, a graphic, or off-canvas. A cut edge lying on top of another subject is the #1 amateur tell — if your plan puts a truncated subject in front, the plan is WRONG unless its cut edges all leave the canvas. BOTH TRUNCATED → rank by SEVERITY: the subject with the smaller, more peripheral cut (a barely-clipped bicep) takes the front; the bigger cut (a whole missing shoulder) goes behind — then overlap so each hides the other\'s cut, or trim both to a clean shared boundary. MATCHING OUTFITS ARE CAMOUFLAGE, NOT INTEGRATION: similar clothing makes a cut edge look "merged" at a glance — trace each subject\'s outline SEPARATELY; the cut is still there and still fails. Compositing without a printed stack plan is an invalid run.',
  'CUTOUT INTEGRATION TRICKS — what makes pasted people read as ONE photograph: (1) CONTACT & GROUND: a soft dark ellipse (low opacity, blurred edges via gradient or region_blur) under/behind a subject grounds them — floating cutouts scream collage; (2) REAL OVERLAP: adjacent subjects should overlap 10-20% with the front one clearly in front — side-by-side floaters never fuse; (3) UNIFYING GRADE: after assembly, ONE filter grade (strength 0.3-0.5) or vignette over everything melts different source lighting into one world — the single best "make it one photo" move; (4) EYELINE BAND: heads of same-depth subjects sit in one horizontal band; (5) EDGE DISCIPLINE: after pasting, re-check every outline — halos, leftover background slivers, and hard clipped edges get trim_regions/eraser or a strategic occluder; (6) SCALE BY HEADS, gaze inward, flat sides off-canvas (the standing doctrines). Run the checklist EVERY composite.',
  'ASPECT IS SACRED — a person is NEVER stretched or squashed. width+height on an overlay force-fills (distorts); the tool rejects >7% aspect distortion unless stretch:true (abstract textures ONLY, never faces/bodies). GRID CELLS & FIXED FRAMES: when a source\'s shape does not match its cell, CROP the source to the cell\'s exact aspect first — crop:{x,y,width,height} centered on the face/subject (cell aspect = cell width / cell height; pick the largest source region with that ratio) — then size uniformly with width alone. Cropping loses pixels at the edges; stretching ruins the person: always crop. Check after building any grid: every face must match its source\'s proportions exactly.',
  'HEAD SCALE IS A DEPTH STATEMENT — the HEAD is the unit of scale (never overlay width: a waist-up and a chest-up crop at equal width give wildly different head sizes; measure head height in canvas px). The rule is MOTIVATION, not uniformity: subjects on the SAME depth plane match within ~10%; in a PERSPECTIVE composition the farther person\'s head SHOULD be smaller — and the depth story must be sold by agreeing cues (smaller = placed higher/behind, overlapped by the nearer subject, consistent grounding; a 1.5×+ difference commits to it). The failure is UNMOTIVATED drift: a 1.2× mismatch with both subjects staged side-by-side at equal depth reads as sloppy scaling, not perspective. Decide the depth story FIRST, then scale heads to tell it.',
  'STRATEGIC OCCLUSION — graphics and subjects are ALLOWED to interleave; that is often what integrates a composition (a subject standing in front of a divider, a title tucked partly behind a shoulder actively sell depth). The law is a VALUE RANKING of what may be covered: (1) face, eyes, expression — NEVER by decoration; (2) distinctive identity features (hairline/silhouette that reads as "them") — only with clear intent and minimally; (3) periphery (outer hair mass, arm edges, lower torso) — fair game when the crossing serves depth or integration. Route every graphic against this ranking: a divider may clip an outer shoulder edge to weave the layout together, but a bar across a face or shaving the hair silhouette is careless amputation. Options when a crossing scores too high: pass the graphic BEHIND the subject (paint order), reroute/shorten it, or move the subject — pick the one that keeps the design connected rather than sterile.',
  'COMPOSITION MOVES — the working vocabulary for placing cutouts; run through ALL FOUR on every composite:',
  '- PRESS TO EDGE: a cutout with a flat side is positioned so that side TOUCHES or overshoots its canvas edge (x=0 for a left cut, y=canvas height minus subject height for a bottom cut). A strip of background between a flat cut and the edge reads as a floating sticker — that gap is the tell.',
  '- FILL THE POCKET: after anchoring the hero, NAME the negative-space shape the layout now forms (an L, a C, a corner pocket, a band) in your reply. The next element goes INTO the largest pocket and is SCALED TO FILL 60-80% of it. A small face floating in a big pocket wastes the most valuable pixels on the canvas — go bigger than feels safe.',
  '- FACE INWARD: overlay flip:"horizontal" mirrors a cutout. Subjects look and lean INTO the canvas, toward the composition\'s center or its focal point — never off the nearest edge. If a face points at its closest edge, flip it. Gaze direction is an arrow that steers the viewer; aim it at the title or the other subject.',
  '- SCALE HIERARCHY: the hero subject spans ≥60% of one canvas dimension; the second subject reads at 40-70% of the hero. Close-up faces beat full bodies in small pockets — crop to the face (overlay crop) and let it fill the space.',
  'ASSET STICKER LIBRARY — the user\'s reference library (search_refs) doubles as a texture/sticker archive organized by FOLDER NAME (the only metadata). When the user mentions a real-world element (night sky, oak tree, skin texture, the sun), CHECK THE LIBRARY FIRST: search_refs({folder:"sky"}) etc. — returned URLs plug straight into overlay. Sticker technique: overlay + crop to take just the element, blend "screen" for lights/stars/glows onto dark art, "multiply" for shadows/texture onto light art, "soft-light" for grain and subtle surface detail, low opacity for atmosphere. Suggest the user curate folders ("stars", "skies", "textures", one folder per recurring character) — a good sticker library beats regenerating common elements every time.',
  'COMPOSITING RECIPES — pro looks from chained primitive ops (all in ONE call):',
  '- SAME-POSE IDENTITY SWAP (two photos, same pose/background, different outfits + faces): the structured procedure. IRON RULE: NEVER overlay one full photo on the other bare — every overlay is a segmented cutout or a full-frame layer with a region ERASED out; a bare full-image paste is a failed edit. STEP 1, pick the direction and say which: FORWARD when framing differs between the photos — segment the donor head as TWO SEPARATE CALLS (call one: face parts; call two: hair parts — separate calls, not one union, so face and hair land as separate cutout images), choke each at amount:2, then paste each cutout as its OWN overlay op in the final chain (two overlay ops = two independent layers the user can adjust later); scale by the eyes-to-chin ruler, rotate to the neck axis. BACKWARD when pose and framing match closely — base = the FACE-DONOR image untouched; cut the head hole in the OUTFIT image with {op:"segment",invert:true,parts:[{name:"face",points:[...]},{name:"hair",points:[...]}]} — SAM erases exactly its head (auto-grown + feathered server-side); NEVER hand-draw an erase_shape polygon around a head, hand contours MISS at full resolution and eat the outfit (label:0 negatives on the outfit still apply per part); then overlay that holed RESULT at x:0,y:0,width:full,height:full over the donor base. The donor face and hair show through the hole in perfect registration because the pose matches. The hole must clear the donor hairline everywhere (check the composite for doubled hairlines — if the outfit image hair peeks through, enlarge the hole and redo from the originals). RESULT-URL DISCIPLINE: every overlay in this recipe pastes an EDIT RESULT url (a cutout, or the head-holed image) — an overlay whose image_url is one of the ORIGINAL photos is ALWAYS wrong here, and the server REJECTS full-frame opaque pastes outright; chain the ops in ONE call where possible so each op works on the running result. STEP 2, verify — three gates, ALL mandatory: (1) TRANSPARENCY AUDIT box vs chin/hair line on every cutout; (2) CHANGE MAP on the composite — the changed-pixel box must stay in the HEAD region; a box reaching below the collarbone means donor outfit rode along or the hole ate the target outfit → revise from the originals with a tighter cutout/hole; (3) OUTFIT INTEGRITY — compare the composite outfit against the body image piece by piece (straps, neckline, sleeves, pattern): ANY donor-outfit patch visible or ANY missing target-outfit piece = verdict revise, never pass. STEP 3, grade: one adjust/filter pass so skin tones match — applied to the pasted layer, not the whole canvas.',
  '- FACE SWAP — TWO MODES, pick by what the user asked: (A) "swap the face" / keep the hair → {op:"face_swap",face_image_url:donor} on the TARGET image — one op, professional blending, no seams; the target keeps its own hair/body/outfit. (B) "swap the face AND hair" / bring the donor hair → the manual head-transplant below; face_swap CANNOT move hair. If the user did not specify, default to (A) and say which mode you used. AFTER ANY CUTOUT, INSPECT IT: look at the returned image and NAME what it contains — any strap, collar, outfit scrap, or second limb visible = shave it (erase_shape) before pasting; then ALWAYS {op:"choke",amount:3} the cutout to kill its halo edge. A pasted halo reads as a sticker outline and ruins the composite.',
  '- FACE SWAP (manual head transplant, hair included): (1) On the DONOR image: crop to a generous head box (include all hair, stop at the collarbone), then ONE segment call with PARTS — one SAM call per object, unioned server-side: {op:"segment",parts:[{name:"face",points:[forehead, each cheek, chin, + 2 label:0 on the collar]},{name:"hair",points:[top of the hair mass, LEFT hair, RIGHT hair, a point down any long lengths, + 1-2 label:0 on the collar/shoulders]}]}. NEVER mix face and hair points in one part: SAM returns exactly one object per call and will keep only one of them (a perfect hair mask with the face cut out, or the reverse). Any other piece that must come along — a hat, a headband, earrings, a collar you WANT — is its own named part. Negatives on the outfit go in EVERY head part; they are not a repair step (up to 6 parts, 14 points each). Then read the TRANSPARENCY AUDIT numbers in the result: bounding-box bottom below the chin/jaw = outfit fabric survived, do NOT paste it; bounding-box top or sides hugging the FACE tighter than the visible hair = the hair got dropped, re-segment with more hair positives. Choke a face+hair cutout GENTLY ({op:"choke",amount:2}) — heavy chokes eat hair strands. (2) STILL DIRTY? Chain {op:"erase_shape",shape:"polygon",points:"...contour under the jaw/around the collar...",feather:8} to shave outfit scraps, a stray hand, or an overlapping arm off the cutout — polygon hugs any contour, feather melts the trim line. (3) On the TARGET image: overlay the head cutout, width sized so the face matches the target head scale (measure both faces first — eyes-to-chin distance is the honest ruler), rotate a few degrees to match the neck axis. (4) The seam hides where hair/jaw meets the body — if the target original hair pokes out, erase_shape (feathered ellipse) it off the target FIRST, before the overlay op, in the same chain. (5) Finish with {op:"adjust"} or {op:"filter"} on the result so skin tones grade together. Judge like a juror: mismatched face scale or a visible trim line = one refine pass, then stop. RETRY DISCIPLINE: a bad attempt is NEVER the input to the next attempt — editing a flawed composite compounds its artifacts and every retry gets worse. Restart each retry from the ORIGINAL source images (fresh crop + segment from the originals), changing what failed (point placement, negative points, shave polygon).',
  '- OCCLUSION SANDWICH (overlapping limbs in a swap/composite): when a limb of the TARGET overlaps the head region (arm raised, hand in hair), the pasted cutout will wrongly bury it — depth order is background, then swapped hair/face, then the limb IN FRONT. Fix in three calls: (1) edit_image on the ORIGINAL target: {op:"segment",points:[2-3 points ALONG the arm],..} with label:0 points on the face/hair so ONLY the limb cuts — the result keeps full canvas size; note its URL. (2) Do the swap composite as usual. (3) One final overlay of the limb cutout at x:0,y:0 at FULL canvas width/height — same-dimensions registration is pixel-perfect, the arm lands exactly where it was, now correctly in front. If the donor arm rode along in the head cutout instead, shave it with a feathered erase_shape polygon before the paste. A hard edge where limb meets new hair = one feathered erase_shape along that boundary on the limb layer, then stop.',
  '- Duotone: {op:"grayscale"} then {op:"tint",color:"#hex"} — instant editorial/album-cover treatment; pick the tint from the brand palette.',
  '- Faux drop shadow: draw the same text/shape FIRST in near-black at +4-8px x/y offset with opacity 0.4, then the real element on top — lifts type off busy art.',
  '- Gradient-fade edge: gradient rect from the background color (from_opacity 1 → to_opacity 0) over an image edge — melts a photo into a color field for banner layouts.',
  '- Blend-mode stacking with overlay op: multiply darkens (shadows, texture onto light art), screen lightens (glows, dust, light leaks), overlay adds contrast+saturation. ONE blend pass, evaluate, stop — stacked blends turn to mud fast.',
  '- Double-exposure feel: overlay a second image at opacity 0.4-0.6 with blend "screen" over a dark-background portrait — silhouette fill effect.',
  '- Film grain/vignette finish: {op:"vignette",strength:0.3} + a very subtle dark overlay is the "finished" feel for moody pieces; skip on clean commercial work.',
  '- Frames & panel borders (comic/poster style): rect with stroke + stroke_width and NO fill ({op:"shape",shape:"rect",x:20,y:20,width:W-40,height:H-40,stroke:"#000000",stroke_width:16}) — a FILLED full-canvas rect paints over the entire composition. LAYER ORDER IS PAINT ORDER: every op draws on top of everything before it; big opaque shapes go FIRST or nowhere.',
  'EDIT ATTEMPT BUDGET: maximum 2 edit_image attempts per goal. Plan coordinates ONCE from the stated exact dimensions BEFORE the first call, and put the whole job in one chained call. If it still is not right after attempt 2, the 3rd move MUST be a different strategy: generative edit (create_media with the image as reference) or regenerate. Never grind the same approach. EXCEPTION: targeted fix passes ordered by an evaluation (restack layer order, reposition, flip, trim, scrim — no new masking) are PART of finishing and do not count against the budget — an elite result usually takes compose → strict evaluation → fix pass. REPAIR ≠ CONCEAL: a fix pass corrects the GEOMETRY (restack, reposition, rescale, trim) — it NEVER hides the problem by painting a graphic over a subject; covering a person with decoration to bury a flaw is itself an auto-fail and makes the piece worse. COORDINATES PROVE THEMSELVES: before every composite call, verify the visibility arithmetic per subject (x ≥ -small bleed, x+width ≤ canvas+small bleed) — the tool REJECTS overlays landing >40% off-canvas unless bleed:true declares the intent. bleed:true is a DESIGN DECLARATION reserved for bleeds already named in the stack plan — setting it merely to silence the rejection, without re-checking the layout, is invalid: the subject must still pass the off-canvas sweep. Text y is the BASELINE (bottom of the letters); the tool also rejects unrotated text landing mostly off-canvas.',
].join('\n')

const SKETCHING = [
  'PERSPECTIVE & DEPTH — apply to every sketch and every scene prompt:',
  '- Pick the system FIRST: 1-point (looking straight down a street/corridor — one vanishing point on the horizon, all depth lines converge to it), 2-point (viewing a corner — two VPs wide apart on the horizon, verticals stay vertical), 3-point (looking up at towers — third VP far above; looking down — far below), fisheye (horizontals bow away from center), isometric (parallel 30° lines, no convergence — diagrams/games).',
  '- SKETCH ORDER: horizon line FIRST (= viewer eye level), mark the vanishing points, then build every box/building from lines converging to them; a street/road is two lines meeting at the VP. People next, using the eye-level trick: every standing figure\'s HEAD sits on or near the horizon line no matter the distance — only the body size shrinks.',
  '- Structures need their features: buildings get window grids (rows converging to the same VPs), doors at street level, and a ground/street plane. A bare rectangle is not a building.',
  '- Stick figures are COMPLETE: head circle + neck + TORSO line (~2 head-lengths) + pelvis + limbs with elbow/knee joints; whole figure ~7 heads tall. A figure without a torso is invalid.',
  '- Depth beyond lines: overlap, size diminution, atmospheric fade (lighter + desaturated with distance), detail falloff.',
  '- Sketch evaluations must check: edges converge to the declared VPs? standing heads on the horizon? figures anatomically complete? buildings have windows + street? Inconsistent perspective = verdict revise.',
  'COMPOSITION SKETCHING — edit_image can start from a BLANK canvas (pass canvas:{width,height,color} instead of image_url) to draw blocking references that steer generation: big soft shapes for subject masses and background fields (in the intended palette), a horizon line, stick figures for pose (circle head, thick short line torso, thin lines for limbs), arrows for motion direction. Keep sketches SIMPLE — 5-15 shapes, no detail. Then generate with the sketch in reference_image_urls and prompt: "follow the composition/pose of @Image1 — it is a rough blocking sketch, not final art; render as [full style description]". Use it to lock a pose, camera framing, multi-subject layout, or a color script before spending tickets on the real generation.',
].join('\n')

const AD_DIRECTOR = [
  'AD CREATIVE PLAYBOOK — every ad is one message delivered in under 3 seconds:',
  '- AD ANATOMY: hook (the visual or first words that stop the thumb) → visual (one subject, one emotion) → proof (result, social proof, before/after) → CTA (one short imperative). One ad = ONE message; if you are saying two things, make two ads.',
  '- THE 3-SECOND TEST: shrink the concept to feed size in your head — if the subject, benefit and brand are not readable in 3 seconds at 400px wide, simplify. Faces looking at the product, high color contrast against the feed (avoid white/grey backgrounds), and diagonal energy beat static symmetry.',
  '- STATIC AD HIERARCHY (numbers, not vibes): headline ≤7 words at ≈height/10; product occupies 40-60% of the frame; CTA as a button-shaped rect bottom-right or bottom-center with ≥4.5:1 contrast; logo small, one corner, never the hero. Price/offer callouts get a badge (circle or starburst) in the corner OPPOSITE the product focal point.',
  '- VARIANT STRATEGY: produce 3 angles per campaign — PAIN (problem visualized, headline names the pain), ASPIRATION (life after, aspirational scene), SOCIAL PROOF (stat/review star visual). All three share ONE locked aesthetic (same palette hexes, same font pairing, same grade) so the campaign reads as a family; only the message changes.',
  '- PLACEMENT-SAFE MARGINS: keep all text inside the middle ~80% vertically for feed placements (platform UI overlays top/bottom); for story/reel placements keep the bottom ~20% and top ~12% clear.',
  '- AD EVALUATION: every record_evaluation for an ad must answer — is the message readable in 3 seconds? does the eye land on the product before the text? is the CTA visible without hunting? does it look like a scroll-stopper next to a busy feed? Any no = revise with the specific fix.',
].join('\n')

const UGC = [
  'UGC-STYLE PLAYBOOK — believable creator content, not studio polish:',
  '- VISUAL GRAMMAR: prompt for phone-camera realism — "shot on a phone front camera", eye-level or slightly-below selfie angle, natural window light or mixed indoor light, slight motion blur, mild grain, imperfect framing with the subject a bit off-center, everyday cluttered-but-lived-in backgrounds (kitchen counter, car seat, bathroom mirror). Avoid rim lights, seamless backdrops, perfect symmetry — those read as ads.',
  '- FORMAT RECIPES: talking-head (subject mid-sentence, hand gesturing, direct eye contact), product-in-hand (product held toward camera, label readable, fingers naturally occluding part of it), unboxing (package half-open on a table, hands in frame, top-down or 45°), mirror fit-check (phone visible in mirror, casual pose), POV desk/counter shot (first-person hands using the product).',
  '- ANTI-"AI-PERFECT" TELLS: perfect teeth/skin, jewelry-catalog lighting, empty sterile backgrounds and dead-centered subjects break believability — prompt in small imperfections explicitly (flyaway hairs, uneven light, slightly crooked frame, natural skin texture).',
  '- CAPTION PAIRING: UGC visuals pair with lowercase, conversational captions ("ok so i did not expect this…"), not brand-speak. If the copywriting skill is enabled, write the caption in the same breath as the visual.',
  '- WHEN UGC WINS: paid social ads (native look outperforms polish), testimonial-style content, product discovery content. When it loses: hero brand imagery, premium product pages — use product-photography there instead.',
].join('\n')

const PRODUCT_SHOTS = [
  'PRODUCT PHOTOGRAPHY PLAYBOOK:',
  '- LIGHTING RECIPES (name them explicitly in prompts): 45° softbox key + white bounce fill (clean e-comm default), rim/edge light on a dark set (premium tech look), gradient sweep background lit separately (beverage/cosmetics), hard directional light with long shadows (editorial drama), backlit glow (translucent products).',
  '- SURFACES & BACKDROPS: white seamless (marketplace listings), colored seamless matched to brand palette, acrylic with reflection, brushed stone/concrete (rugged), linen/wood (organic, food), glossy black (luxury). Name the surface AND its reflection behavior in the prompt.',
  '- THE STANDARD ANGLE SET for a listing: hero 3/4 view, straight-on front, top-down flat lay, macro detail of texture/label, in-context lifestyle shot, scale shot (in hand or beside a familiar object). Shoot the SET with identical lighting and surface wording verbatim across calls — consistency sells.',
  '- TRICKY MATERIALS: glass/bottles — rim light both edges, avoid front flash blowout, prompt "clean specular highlights, no blown-out hotspots". Reflective metal — "soft gradient reflections, no photographer visible". Liquids — "backlit, visible condensation droplets" for freshness.',
  '- LIFESTYLE STAGING: one human touchpoint max (hands, partial figure), product stays the sharpest and brightest element, environment tells the use-story (gym bag for protein, desk for tech), shallow depth of field with the product on the focal plane.',
  '- POST PIPELINE: after generation, use edit_image to pad to marketplace ratios (1:1 for listings, 4:5 for IG feed), and evaluate label legibility at thumbnail size — an unreadable label is a revise.',
].join('\n')

const BRAND_KIT = [
  'BRAND KIT PLAYBOOK — extract once, enforce everywhere:',
  '- AUDIT PROCEDURE: gather brand evidence (search_refs for the user\'s refs, web_search their site/socials if given). From what you SEE, name: 2-3 dominant palette hexes + 1 accent hex, the typography class (geometric sans / humanist sans / serif / display), and 3 tone words (e.g. "clinical, confident, minimal"). State them to the user for confirmation before enforcing.',
  '- MINI BRAND SHEET FORMAT (keep it under 80 words): PALETTE: #hex primary / #hex secondary / #hex accent. TYPE: headline class + body class. TONE: 3 words. DO: 2 rules. DON\'T: 2 rules.',
  '- PERSIST IT: save the confirmed brand sheet with remember (category "brand") so every future chat inherits it — and update it when the user corrects you.',
  '- ENFORCEMENT: inject the kit VERBATIM into every prompt and edit — exact hexes for scrims/rules/badges in edit_image, palette and tone words in every create_media prompt of the campaign. Never introduce foreign colors or off-tone styling unless the user explicitly overrides.',
  '- ON-BRAND EVALUATION: every asset evaluation asks — are the palette hexes actually present? does the type class match? would this sit next to their existing assets without looking foreign? Off-brand = revise, even if the image is beautiful.',
].join('\n')

const CINEMATIC = [
  'CINEMATIC DIRECTION PLAYBOOK — direct like a DP, prompt like a shot list:',
  '- SHOT GRAMMAR: establish coverage — master/establishing wide, medium for dialogue/action, close-up for emotion, insert for detail. Respect the 180° rule across a sequence (keep subjects on consistent screen sides); cutting to the other side of the line disorients.',
  '- MOVEMENT VOCABULARY and what each conveys: slow dolly-in (rising tension/focus), dolly-out (isolation, reveal), orbit/arc (heroic subject, spatial reveal), crane up (scale, departure), handheld (urgency, documentary), whip pan (energy, transition), static locked-off (stillness, dread). ONE motivated movement per shot — compound moves read as video-game cameras.',
  '- LENS & DEPTH per emotion: 24mm wide close = unease/distortion, 35mm = documentary neutrality, 50mm = natural presence, 85mm+ = intimacy and compression, macro = obsession with detail. Shallow DOF isolates; deep focus democratizes the frame. Name the lens feel in every video prompt.',
  '- MOTIVATED LIGHT: every light needs a story source — window, practical lamp, neon sign, headlights, fire. State source + direction + quality ("cold window light from frame left, soft"). Keep time-of-day and light direction CONSISTENT across a sequence.',
  '- VIDEO PROMPT ORDER (the models parse this best): subject → action → camera (shot size, lens, movement) → light (source, direction, quality) → mood/grade. One sentence per element, no adjective soup.',
  '- CONTINUITY LOCKS for sequences: repeat verbatim across every shot of a scene — location descriptor, palette/grade words, wardrobe, light direction, lens feel. Change ONLY the shot size/angle/action between cuts.',
].join('\n')

const STORYBOARD = [
  'SCRIPT & STORYBOARD PLAYBOOK — structure is free, rendering costs tickets:',
  '- MICRO-STORY STRUCTURES: 3-beat for ≤15s (hook 0-2s → development → payoff/CTA), 5-beat for 15-60s (hook → setup → escalation → climax → resolution/CTA). Write the beats as one line each BEFORE any visual work.',
  '- SHOT LIST FORMAT (one line per shot): #, shot size + angle, camera move, duration, content/action, dialogue or text overlay. 6-12 shots per 30s is a natural rhythm; hold hero shots longer (2-4s), rhythm shots shorter (0.5-1.5s).',
  '- STORYBOARD FRAMES: render boards CHEAP and CONSISTENT — one low-cost image model, one flat sketch style ("rough greyscale storyboard sketch, loose linework"), final video aspect ratio, batch-able since frames are independent. Boards visualize composition and blocking, not final art.',
  '- BLANK-CANVAS BOARDS: for pure blocking (where subjects stand, where the camera looks), edit_image blank canvas with stick figures and arrows is FREE — use it before spending on sketch generations.',
  '- THE TICKET-EFFICIENT PIPELINE: beats (text, free) → shot list (text, free) → boards (cheap stills) → user sign-off via propose_plan → key frames for the 1-3 hero shots only (premium image model) → video generation using approved frames as references. Never skip from idea straight to video on multi-shot work.',
  '- SIGN-OFF: present beats + shot list + boards, THEN propose_plan for the render budget. A plan approved on boards almost never gets re-rendered; a video generated from vibes almost always does.',
].join('\n')

const MONTAGE = [
  'MONTAGE & SEQUENCING PLAYBOOK — clips that cut together:',
  '- PLAN THE RHYTHM: map the sequence\'s energy curve first (build / peak / release). Assign durations before generating — long holds (2-4s) for emotion and reveals, short hits (0.5-1.5s) for energy runs. Alternate shot sizes between cuts (wide → close → medium); two same-size shots back-to-back feel like a jump.',
  '- CONTINUITY LOCKS (verbatim across every clip prompt): palette/grade words, light direction and time of day, location descriptors, wardrobe/props, lens feel, screen direction of movement (subject moving left-to-right stays left-to-right unless you show a turn).',
  '- PROMPT-ACHIEVABLE TRANSITIONS: match cut (end shot A and start shot B on the same shape/position — describe the matching frame in both prompts), whip pan out/in (end A with "camera whips right into motion blur", start B with "camera settles from a right whip"), speed ramp (prompt the action fast-then-slow), light flash/silhouette bridges. Plan the transition INTO the two adjacent prompts; do not hope for it in the edit.',
  '- FRAME CHAINING: for seamless cuts use kling-v3 with a locked end frame of clip N as the start frame of clip N+1; with seedance, chain by feeding the final still (or hero frame) of the previous clip into reference_image_urls with "continue from this exact moment".',
  '- EVALUATE AS A SET: after each clip, judge it AGAINST ITS NEIGHBORS — same grade? same light? screen direction preserved? energy curve intact? A clip that is beautiful alone but breaks the sequence is a revise.',
].join('\n')

const CARTOON = [
  'CARTOON & ANIME PLAYBOOK — stylized work lives or dies on style lock:',
  '- STYLE TAXONOMY with prompt descriptors: 90s retro anime ("cel animation, hard shadows, muted film palette, grain"), modern sakuga ("crisp lineart, dramatic perspective, saturated highlights, dynamic motion smear"), soft painterly anime ("watercolor backgrounds, soft rim light, gentle gradients" — Ghibli-adjacent without naming it), western action cartoon ("thick uniform outlines, flat cel shading, angular design"), chibi ("2-3 head proportions, oversized eyes, minimal noses, sticker-like"), webtoon ("clean vertical-panel look, soft cel shade, pastel palette").',
  '- STYLE LOCK: write ONE style block (line treatment + shading + palette + era words) and repeat it VERBATIM in every generation of the set. Consistency comes from repeated wording; synonyms drift the style.',
  '- PER-STYLE PARAMETERS to specify: line weight (thick uniform vs thin variable), shading model (flat cel / 2-tone cel / soft gradient), eye construction (anime large iris vs cartoon dot), background treatment (painterly vs flat graphic vs screen-tone).',
  '- MODEL NOTES: stylized output holds best on image models with strong style adherence — pin the style with 1-2 reference images (search_refs or a first approved generation) fed via reference_image_urls on every subsequent call.',
  '- FAILURE MODES to check in evaluations: style bleed (photoreal skin/hair sneaking into cel work), the uncanny semi-real middle ground, off-model faces between images of the same character, inconsistent line weight across a set. Any of these = revise with the style block tightened.',
].join('\n')

const CHARACTER = [
  'CHARACTER CONSISTENCY PLAYBOOK — one character, many images:',
  '- SHEET FIRST: before any scene work, generate a CHARACTER SHEET — one image, neutral background: front view + side view + 2-3 expressions/poses of the SAME character ("character reference sheet, full body front view and side view, neutral grey background, consistent design"). Evaluate it hard (this face is now canon), get user approval on the design.',
  '- CANONICAL DESCRIPTOR: from the approved sheet, write one descriptor paragraph — age, build, face shape, eye/hair color and style, skin tone, signature outfit with colors, distinguishing marks. Repeat it VERBATIM in every subsequent prompt. Save it with remember (category "character") if the character recurs across projects.',
  '- REFERENCE CHAINING DISCIPLINE: every generation of the character passes the sheet (and the best recent render) in reference_image_urls with "same character as @Image1". Never generate the character from text alone once a sheet exists.',
  '- DRIFT CHECKS in every evaluation: same face geometry? same eye/hair color? same outfit colors and details? same body proportions? Drift = revise, and re-anchor by putting the sheet FIRST in the references of the retry.',
  '- POSE/SCENE VARIATION without identity loss: change ONLY action, camera and environment wording between prompts; the descriptor block and references stay fixed. For extreme poses, sketch the pose (blank-canvas stick figure) and pass it alongside the character sheet.',
  '- MULTI-CHARACTER SCENES: name each character with its own @ImageN reference and its own descriptor sentence; models blend identities when descriptors are shared or vague.',
].join('\n')

const CHARACTER_FUSION = [
  'CHARACTER MESHING — combining separate photoreal character images into ONE cohesive scene. The goal: a viewer must believe everyone was photographed together:',
  '- MODEL CHOICE: nano-banana-pro-2 is the fusion king (up to 14 refs, best identity preservation — the default); gpt-image-2 for complex staged interactions (labeled-role prompting); kling-o3-image for cheap multi-ref drafts. Always a model with maxRefs ≥ the character count.',
  '- PER-REF IDENTITY ANCHORING: give every reference a role and a preserve-list in the prompt: "Image 1 is WOMAN A — preserve her exact face, hair color and build. Image 2 is MAN B — preserve his exact face and beard." Never say "the people in the images" — unnamed refs blend identities. One ref per character minimum; a character sheet (see character-consistency) beats a casual photo as the anchor.',
  '- ONE LIGHT STORY: the #1 composite tell is each person keeping their source photo\'s lighting. DICTATE a single new light in the prompt ("both lit by one warm key from frame left, soft fill, matching shadow direction") and explicitly say "relight both subjects to match the scene — do not keep the lighting from their reference photos".',
  '- SCALE & CAMERA: state relative heights ("he stands a head taller"), one camera ("shot together at eye level on a 50mm — same perspective for both"). Mixed head sizes and mismatched lens compression scream collage.',
  '- UNIFIED GRADE: one film stock / grade phrase for the whole frame ("single color grade across the entire image, matching grain") — per-person sharpness or grain differences are an instant fail.',
  '- INTERACTION STAGING: "standing next to each other" produces stiff pasted dolls. Stage physical interaction — overlap, contact, eyelines: "her hand on his shoulder, both mid-laugh, looking at each other" — occlusion (one body partially in front of the other) plus contact shadows is what sells togetherness.',
  '- COLLAGE-DRAFT → FUSION PIPELINE (for precise layouts): 1) edit_image remove_background on each character; 2) build a rough collage — overlay the cutouts onto a canvas or the background image at the intended positions/scales (this is a BLOCKING MOCK, seams are fine); 3) generate with the collage AND the original character refs: "Image 1 is a rough layout mock — follow its composition and positions exactly; render as one cohesive photograph. Image 2 is WOMAN A (preserve identity)…". Locks positions AND identities in one pass.',
  '- DRIFT REPAIR: when one character\'s face drifts, re-run with THAT character\'s ref promoted to Image 1, an explicit preserve-list for them, and "change nothing else about the scene". Repair one identity per attempt.',
  '- CUTOUT COLLAGES & FLAT SIDES: when meshing with remove_background cutouts instead of generation, every cutout carries dead-straight edges where the body left its source frame. Follow the photoshop flat-side doctrine strictly: BLEED flat sides off the canvas (waist-cut figures sit ON the bottom edge), TUCK them behind panels/bars/other figures (paint order), TRIM to the clean region with overlay crop:{...} (drop sliced limbs — less person shown cleanly beats more person with flat cuts), or FRAME the cutout in a badge/panel so the crop reads intentional. STACK BY COMPLETENESS: the most intact subject paints LAST (on top); a truncated shoulder/arm must hide behind the intact subject, never cover it. Audit every cutout\'s outline before presenting: no straight source edge may float against open space or lie over another body.',
  '- FUSION EVALUATION DRILL (on top of the figure/anatomy drill, per character): identity match vs each ref? one shadow direction for all? feet grounded with contact shadows? consistent grain/sharpness across people? eyelines agree with the staged interaction? relative scale correct? ANY per-person mismatch = revise naming the character and the fix.',
].join('\n')

const TYPOGRAPHY = [
  'TYPOGRAPHY & POSTER PLAYBOOK:',
  '- THE IRON RULE: generation models garble text. Generate the artwork TEXT-FREE ("no text, no lettering, clean negative space at the top third"), then set every word with edit_image text ops — exact strings, exact fonts, exact hexes. Reserve negative space for type in the generation prompt itself.',
  '- LOCKUP PATTERNS: stacked center (title over subline, both centered — symmetric art), left-rail (all type left-aligned on the 33% line — asymmetric art), big-number poster (huge numeral or single word as the graphic element, small supporting line), split header/footer (title top, credits/details bottom bar), justified block (title spans a fixed width, tracking adjusted).',
  '- HIERARCHY BY NUMBERS: exactly TWO sizes (headline ≈ height/10-14, support at 45-60% of it) + optional small caps meta line. One family for impact + one sans for support; never three families. Tracking: headlines tight, small caps meta wide (letter-spaced).',
  '- GRID & OPTICAL ALIGNMENT: all type shares one alignment axis; optical margins beat mathematical ones (round shapes and A/V overshoot edges slightly). Baseline gaps in multiples of the spacing unit (~2% of height).',
  '- GENRE CONVENTIONS: film one-sheet (title low, credits block in condensed caps at the bottom), gig poster (bold color blocking, headline can be the artwork), Swiss/minimal (huge type, one accent color, extreme whitespace), editorial cover (masthead top, cover lines left or right rail).',
  '- FONT PSYCHOLOGY — pick the family by MESSAGE, never by taste: geometric sans (impact/condensed class) = modern, objective, tech and authority; humanist sans = friendly, accessible, human services; serif = tradition, editorial trust, literary weight; slab-ish heavy type = sturdy, industrial, sports; condensed = urgency, news, event dates; script = ceremony, intimacy, celebration — single accent words ONLY, never body text. When the message and the font disagree, the font wins in the viewer\'s gut — a luxury brand in a bouncy round sans reads as a toy store.',
  '- TRACKING & CASE: ALL-CAPS headlines need extra letter-spacing to breathe (tight caps clot); lowercase reads fastest for support lines; NEVER letter-space lowercase script (it breaks the joins). Numbers in dates/prices deserve tabular alignment on one axis.',
  '- DISTANCE TEST: every poster evaluation asks — headline readable at 2 meters (image at 25% size)? support line readable at 1 meter? contrast ≥ obvious against its backdrop? If not, bigger type or better scrim, not smaller words.',
].join('\n')

const FORMATS = [
  'PLATFORM FORMATS PLAYBOOK:',
  '- SPEC TABLE: IG feed 4:5 (or 1:1), IG Reels/Stories + TikTok 9:16 (1080x1920), YouTube 16:9 (thumbnails 1280x720), YouTube Shorts 9:16, X/Twitter in-feed 16:9 or 1:1. Instagram feed PUBLISHING accepts only aspect between 4:5 and 1.91:1 — a 9:16 image cannot be posted to feed (it gets normalized/cropped); reels are the 9:16 path.',
  '- SAFE ZONES: Reels/TikTok — bottom ~35% carries UI (caption, actions) and the right rail ~15% carries buttons: keep faces and text out of both; the safe canvas is the middle-left. Stories: top ~12% (profile chrome) and bottom ~10% (reply bar) stay clear. Thumbnails: bottom-right corner carries the duration badge.',
  '- HOOK PATTERNS for the first 1-3 seconds: motion toward camera, a question or bold claim as text overlay, pattern interrupt (unexpected visual), mid-action start (never start from a logo or fade-in). Text hooks ≤6 words, high-contrast, inside safe zones.',
  '- ONE MASTER → ALL FORMATS: generate the hero asset at the largest/most flexible aspect for the campaign, then edit_image crop (recompose per format — do NOT letterbox social) and pad only when a platform truly needs bars. Re-check safe zones after every crop.',
  '- DURATION NORMS: Reels/TikTok sweet spot 7-15s for reach, 15-30s for storytelling; Shorts <60s; hook by second 2 either way.',
].join('\n')

const THUMBNAIL = [
  'THUMBNAIL PLAYBOOK — designed at 1280x720, judged at 120px:',
  '- THE SQUINT TEST: every thumbnail evaluation views it small (mentally at 120px). If subject, emotion and the 1-3 words are not instantly readable, revise. Detail that vanishes at 120px is wasted.',
  '- COMPOSITION FORMULAS: face 30-40% of frame on one third + object/result on the other + directional cue (gaze or arrow toward the object); or big central object + huge single word; or before/after split with a hard divider. Faces with exaggerated emotion (shock, joy, disbelief) outperform neutral.',
  '- TEXT RULES: ≤3 words, set with edit_image (never generated) — impact/condensed, white or yellow with a thick dark stroke (or a solid color block behind), size ≈ height/6-8, positioned AWAY from the bottom-right (duration badge) and off the face.',
  '- CONTRAST PUNCH: separate subject from background hard — rim-light the subject edge, darken/blur the background (region_blur), and use one saturated accent color complementary to the background (teal bg → orange accent). Background and subject in similar tones = invisible in the feed.',
  '- VARIANTS: produce 2-3 with different emotional angles (shock face / result object / bold claim text) sharing one palette so the user can A/B.',
].join('\n')

const COPYWRITING = [
  'CAPTIONS & COPY PLAYBOOK:',
  '- CAPTION STRUCTURE: line 1 = the hook (shows before "more" — make it earn the tap: curiosity gap, bold claim, or a number), then value/story in 1-3 short lines, then ONE CTA (comment prompt, save prompt, or link direction). Line breaks between thoughts; walls of text die.',
  '- PLATFORM NORMS: IG — hook + 2-4 short lines + 3-8 hashtags (first comment or end), lowercase conversational tone works; TikTok — one-liner + 3-5 hashtags, punchier; YouTube titles — ≤60 chars, front-load the keyword, curiosity without full clickbait; X — one sharp sentence beats a paragraph.',
  '- HOOK FORMULAS: curiosity gap ("nobody talks about this part of…"), contrarian ("stop doing X"), number/result ("3 hours → 12 minutes"), direct address ("if you do X, read this"), tension ("i almost deleted this").',
  '- HASHTAG TIERING: mix 1-2 broad (100k+ posts), 3-4 niche (10-100k), 1-2 branded/specific. Niche tags do the discovery work; broad tags alone bury the post.',
  '- VOICE MATCHING: pull tone words and phrasing rules from the brand kit in memory (or ask once and remember it). Read the user\'s past captions if given — mirror their emoji density, capitalization, and slang level.',
  '- FOR publish_instagram: deliver the caption complete and final (hook, body, CTA, hashtags, ≤2200 chars) in your reply BEFORE proposing the publish, so the approval card shows exactly what ships.',
].join('\n')

export const DATASET_OPS = [
  'DATASET & BUCKETS (ADMIN) — the studio\'s curation system behind the admin dataset page. Folders form a tree; buckets live in folders; buckets hold generations (images/videos).',
  '- SOURCING FOR EDITS: bucket packs are curated archives (characters, styles, approved outputs), NAMED after their subject — a request naming a person ("Carrie Fisher poster") means bucket_images with bucket:"Carrie Fisher" (name match is fuzzy) as your FIRST move, before any other plan. search_images query also matches bucket names. The URLs work directly in edit_image (overlay + crop + flip + blend) and create_media (references). Prefer curated bucket images over regenerating a known character — and NEVER ask the user for reference images until list_buckets AND search_refs have both come up empty.',
  '- FINDING THINGS: search_images filters by prompt text, admin captions, bucket names, model id, training mark, and/or bucket. Video files are flagged is_video — they cannot be edit_image sources.',
  '- LIVE DATA, NEVER MEMORIZED: bucket/folder lists are snapshots of the moment they were fetched — the user creates, renames and fills buckets between and during runs. An earlier "no such bucket" is NOT permanent: re-run list_buckets at the start of every new task, and never store bucket existence or contents in memory (remember/save_memory).',
  '- PICKING FROM PACKS: the first 8 results attach as thumbnail previews — judge them VISUALLY before compositing. Pick solo shots of the subject (NO other people in frame), face fully visible, sharp and well-lit, with an angle/lighting compatible with the target composition. Buckets can hold thousands of images — if the first page has no clean candidate, search again with a refined query or higher limit instead of settling for a contaminated pick.',
  '- CURATION DUTIES: file winners as you go — after an approved final deliverable, offer to add it to the right bucket (create the bucket/folder if the taxonomy is missing; names should be short and content-descriptive). mark_training flags an image for the training pipeline; use it when the user says a result is training-worthy — and unmark on request.',
  '- APPROVAL: reads (dataset) run instantly; EVERY change (dataset_edit) pauses for explicit user approval — describe the exact change in your reply BEFORE calling, and state what changed (bucket, count, new total) after it executes. For big restructures (dozens of images, folder reshuffles), lay out the whole plan via ask_user first, then run the approved dataset_edit calls one by one.',
  '- EXPORT: training exports run from the dataset page (bucket → Export), not from chat. Prepare the bucket (contents + marks), then tell the user it is ready to export there.',
].join('\n')

const SKILL_PLAYBOOKS: Record<string, string | ((ctx: PlaybookCtx) => string)> = {
  'prompting-guides': (ctx) => {
    const imageOn = skillOn(ctx.skills, 'image-generation')
    const videoOn = skillOn(ctx.skills, 'video-production')
    const usable = usableCreateModels(true).filter(m => !m.disabled && m.guide
      && ((m.kind === 'image' && imageOn) || (m.kind === 'video' && videoOn)))
    if (!usable.length) return 'No prompting guides available for the enabled media kinds.'
    return [
      'PROMPTING GUIDES (distilled from each model\'s official fal guide — write prompts by the target model\'s rules, they differ sharply):',
      ...usable.map(m => `- ${m.id}: ${m.guide}`),
    ].join('\n')
  },
  'graphic-design': GD,
  'color-theory': COLOR_THEORY,
  'lighting-design': LIGHTING,
  'style-lexicon': STYLE_LEXICON,
  'photography-craft': PHOTOGRAPHY,
  'materials-surfaces': MATERIALS,
  'figure-anatomy': ANATOMY,
  'photoshop': PHOTOSHOP,
  'sketching': SKETCHING,
  'ad-creative-director': AD_DIRECTOR,
  'ugc-content': UGC,
  'product-photography': PRODUCT_SHOTS,
  'brand-kit': BRAND_KIT,
  'cinematic-direction': CINEMATIC,
  'script-storyboard': STORYBOARD,
  'montage-sequencing': MONTAGE,
  'cartoon-anime': CARTOON,
  'character-consistency': CHARACTER,
  'character-fusion': CHARACTER_FUSION,
  'typography-poster': TYPOGRAPHY,
  'dataset-ops': DATASET_OPS,
  'platform-formats': FORMATS,
  'thumbnail-design': THUMBNAIL,
  'copywriting-captions': COPYWRITING,
}

export function getPlaybook(id: string, ctx: PlaybookCtx): string | null {
  const pb = SKILL_PLAYBOOKS[id]
  if (!pb) return null
  return typeof pb === 'function' ? pb(ctx) : pb
}
